---
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "turnstone"
  namespace: "turnstone"
spec:
  baseDomain: "wpc.test"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.21-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
    - clusterName: "turnstone"
      networkType: "OVNKubernetes"
      installConfigOverrides: "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
      cpuPartitioningMode: AllNodes
      clusterLabels:
        common-du-414: true
        group-dellxr12-sync: "" # group with ptpconfig
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        #- cidr: fd01::/48
        #  hostPrefix: 64
      machineNetwork:
        - cidr: 192.168.49.0/25
        #- cidr: 2600:52:7:300::0/64
      serviceNetwork:
        - 172.30.0.0/16
        #- fd02::/112
      additionalNTPSources:
        - clock.cars2.lab
      # - clock-v6.cars2.lab
      # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
      # crTemplates:
      # KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
      # proxy:
      # httpProxy: http://cars2-client.infra.cars2.lab:3128
      # httpsProxy: http://cars2-client.infra.cars2.lab:3128
      # noProxy: ".cars2.lab,2600:52:7:300::0/64,fd02::/112,fd01::/48,2600:52:7:300::177,2600:52:7:300::179,2600:52:7:300::180,2600:52:7:300::181"
      nodes:
        - hostName: "xr12-u5.turnstone.wpc.test"
          role: "master"
          # Optionally; This can be used to configure desired BIOS setting on a host:
          # biosConfigRef:
          # filePath: "example-hw.profile"
          bmcAddress: "idrac-virtualmedia://192.168.49.175/redfish/v1/Systems/System.Embedded.1"
          bmcCredentialsName:
            name: "xr12-u5-bmc-creds-secret"
          bootMACAddress: "30:d0:42:d9:e2:12"
          # Use UEFISecureBoot to enable secure boot
          bootMode: "UEFI"
          rootDeviceHints:
            deviceName: "/dev/disk/by-path/pci-0000:00:17.0-ata-5.0"
          nodeNetwork:
            interfaces:
              - name: eno8303np0
                macAddress: "30:d0:42:d9:e2:12"
              - name: eno8303np1
                macAddress: "30:d0:42:d9:e2:13"
              - name: eno8303np2
                macAddress: "30:d0:42:d9:e2:14"
              - name: eno8303np3
                macAddress: "30:d0:42:d9:e2:15"
            config:
              interfaces:
                - name: eno8303np3
                  type: ethernet
                  state: down
                - name: eno8303np2
                  type: ethernet
                  state: down
                - name: eno8303np1
                  type: ethernet
                  state: down
                - name: eno8303np0
                  type: ethernet
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: "192.168.49.75"
                        prefix-length: 25
                    dhcp: false
                  #ipv6:
                  #  enabled: true
                  #  address:
                  #    - ip: "2600:52:7:300::151"
                  #      prefix-length: 64
                  #  autoconf: false
                  #  dhcp: false
              dns-resolver:
                config:
                  search:
                    - wpc.test
                  server:
                    - 192.168.38.12
                    #- 2600:52:7:38::12
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 192.168.49.1
                    next-hop-interface: eno8303np0
                  #- destination: ::/0
                  #  next-hop-address: 2600:52:7:300::1
                  #  next-hop-interface: eno12399np0
