#oc create secret generic assisted-deployment-pull-secret -n turnstone --from-file=.dockerconfigjson=/home/redhat/pull-secret-fun/pull-secret-prega414-final.json --type=kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Secret
metadata:
  name: assisted-deployment-pull-secret
  namespace: turnstone
stringData:
 .dockerconfigjson: ''
