---
# yamllint disable rule:line-length
# yamllint disable rule:comments-indentation
apiVersion: ran.openshift.io/v1
kind: SiteConfig
metadata:
  name: "shadowman"
  namespace: "shadowman"
spec:
  baseDomain: "cars2.lab"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  clusterImageSetNameRef: "img4.14.30-x86-64-appsub"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDd7Jj5iFCWv9IHJK9H+2O3lyPs36moAxeAUiHvzRS3uzqGxxB33BnTRBNDKsoDFSGJX0J4bd5b+XyCPdhFOfvn/xhmAcm6d8GALS+139e8d+No8h2QgZy0OVJFp844k4nmz4wew5/+X9DN40ZURYerekbVc58hw1+rTu0uM2jQ0cE2QmEf3qGKHx9UJW8t6IsMzwnrikBH30sYqn2NcBE+/c8JzlLc3PvvenlY0iQkpukI1A5E9GGMR9OS/q+w6FH85zvSgUatOV7Q5lg45QUF+V77DrfX5+niI+NK1g70pRvD8481SAdXrHPB5vK4vQEmJ4pz83IKYHVuPzRnjzYKv1jV33oReyyMqyk44Rsfkxl4i5SJ9z7q/EVmTjvurzD6ofi3Dg0+PL18eTcjuPFdCxSCUFsnr5N9CRHCxHRQpxoZTD7sYD4jDGNygawLvhxcvgKGBZzP53NRCzRFOMFmZsLPLQRaNOsgKRPAohmrn5l8+1xG5ltVauOwAFlKUxk="
  clusters:
    - clusterName: "shadowman"
      networkType: "OVNKubernetes"
      #installConfigOverrides: "{\"capabilities\":{\"baselineCapabilitySet\": \"None\", \"additionalEnabledCapabilities\": [ \"marketplace\", \"NodeTuning\" ] }}"
      clusterLabels:
        sites: "shadowman"
      clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
        - cidr: fd01::/48
          hostPrefix: 64
      machineNetwork:
        - cidr: 192.168.38.128/26
        - cidr: 2600:52:7:300::0/64
      # For 3-node and standard clusters with static IPs, the API and Ingress IPs must be configured here
      apiVIPS: 
        - 192.168.38.177
        - 2600:52:7:300::177
      ingressVIPs: 
        - 192.168.38.178
        - 2600:52:7:300::178
      serviceNetwork:
        - 172.30.0.0/16
        - fd02::/112
      additionalNTPSources:
        - clock.cars2.lab
        #- clock-v6.cars2.lab
      # Optionally; This can be used to override the KlusterletAddonConfig that is created for this cluster:
      # crTemplates:
      # KlusterletAddonConfig: "KlusterletAddonConfigOverride.yaml"
      # proxy:
      # httpProxy: http://cars2-client.infra.cars2.lab:3128
      # httpsProxy: http://cars2-client.infra.cars2.lab:3128
      # noProxy: ".cars2.lab,2600:52:7:300::0/64,fd02::/112,fd01::/48,2600:52:7:300::177,2600:52:7:300::179,2600:52:7:300::180,2600:52:7:300::181"
      nodes:
        - hostName: "cp1.cars2.lab"
          role: "master"
          # Optionally; This can be used to configure desired BIOS setting on a host:
          # biosConfigRef:
          # filePath: "example-hw.profile"
          bmcAddress: "idrac-virtualmedia://192.168.38.205/redfish/v1/Systems/System.Embedded.1"
          bmcCredentialsName:
            name: "r650-ixcp-2-bmc-creds-secret"
          bootMACAddress: "b0:7b:25:ea:87:62"
          # Use UEFISecureBoot to enable secure boot
          bootMode: "UEFISecureBoot"
          rootDeviceHints:
            wwn: "0x6b07b250e900a6002a99a001ec35a358"
          nodeNetwork:
            interfaces:
              - name: eno12399
                macAddress: "b4:96:91:c8:a9:28"
              - name: eno12409
                macAddress: "b4:96:91:c8:a9:29"
            config:
              interfaces:
                - name: eno12399
                  type: ethernet
                  state: up
                - name: eno12409
                  type: ethernet
                  state: up
                - name: bondctrlplane
                  type: bond
                  mac-address: b4:96:91:c8:a9:28
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 192.168.38.179
                        prefix-length: 26
                    dhcp: false
                  ipv6:
                    enabled: true
                    address:
                      - ip: 2600:52:7:300::179
                        prefix-length: 64
                    autoconf: false
                    dhcp: false
                  link-aggregation:
                    mode: 802.3ad
                    options:
                      lacp_rate: "fast"
                    port:
                      - eno12399
                      - eno12409
              dns-resolver:
                config:
                  server:
                    - 192.168.38.12
                    - 2600:52:7:38::12
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 192.168.38.129
                    next-hop-interface: bondctrlplane
                  - destination: ::/0
                    next-hop-address: 2600:52:7:300::1
                    next-hop-interface: bondctrlplane
        - hostName: "cp2.cars2.lab"
          role: "master"
          bmcAddress: "idrac-virtualmedia://192.168.38.206/redfish/v1/Systems/System.Embedded.1"
          bmcCredentialsName:
            name: "r650-ixcp-2-bmc-creds-secret"
          bootMACAddress: "b0:7b:25:ea:87:62"
          # Use UEFISecureBoot to enable secure boot
          bootMode: "UEFISecureBoot"
          rootDeviceHints:
            wwn: "0x6b07b250e90180002a99a2880fb1b7cc"
          nodeNetwork:
            interfaces:
              - name: eno12399
                macAddress: "b4:96:91:c7:f8:30"
              - name: eno12409
                macAddress: "b4:96:91:c7:f8:31"
            config:
              interfaces:
                - name: eno12399
                  type: ethernet
                  state: up
                - name: eno12409
                  type: ethernet
                  state: up
                - name: bondctrlplane
                  type: bond
                  mac-address: "b4:96:91:c7:f8:30"
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: "192.168.38.180"
                        prefix-length: 26
                    dhcp: false
                  ipv6:
                    enabled: true
                    address:
                      - ip: 2600:52:7:300::180
                        prefix-length: 64
                    autoconf: false
                    dhcp: false
                  link-aggregation:
                    mode: 802.3ad
                    options:
                      lacp_rate: "fast"
                    port:
                      - eno12399
                      - eno12409
              dns-resolver:
                config:
                  server:
                    - 192.168.38.12
                    - 2600:52:7:38::12
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 192.168.38.129
                    next-hop-interface: bondctrlplane
                  - destination: ::/0
                    next-hop-address: 2600:52:7:300::1
                    next-hop-interface: bondctrlplane
        - hostName: "cp3.cars2.lab"
          role: master
          bmcAddress: "idrac-virtualmedia://192.168.38.207/redfish/v1/Systems/System.Embedded.1"
          bmcCredentialsName:
            name: "r650-ixcp-2-bmc-creds-secret"
          bootMACAddress: "b0:7b:25:ea:87:bc"
          # Use UEFISecureBoot to enable secure boot
          bootMode: "UEFISecureBoot"
          rootDeviceHints:
            wwn: "0x6b07b250e902ec002a99a48104fff9e4"
          nodeNetwork:
            interfaces:
              - name: eno12399
                macAddress: b4:96:91:c8:01:5c
              - name: eno12409
                macAddress: b4:96:91:c8:01:5d
            config:
              interfaces:
                - name: eno12399
                  type: ethernet
                  state: up
                - name: eno12409
                  type: ethernet
                  state: up
                - name: bondctrlplane
                  type: bond
                  mac-address: "b4:96:91:c8:01:5c"
                  state: up
                  ipv4:
                    enabled: true
                    address:
                      - ip: 192.168.38.181
                        prefix-length: 26
                    dhcp: false
                  ipv6:
                    enabled: true
                    address:
                      - ip: 2600:52:7:300::181
                        prefix-length: 64
                    autoconf: false
                    dhcp: false
                  link-aggregation:
                    mode: 802.3ad
                    options:
                      lacp_rate: "fast"
                    port:
                      - eno12399
                      - eno12409
              dns-resolver:
                config:
                  server:
                    - 192.168.38.12
                    - 2600:52:7:38::12
              routes:
                config:
                  - destination: 0.0.0.0/0
                    next-hop-address: 192.168.38.129
                    next-hop-interface: bondctrlplane
                  - destination: ::/0
                    next-hop-address: 2600:52:7:300::1
                    next-hop-interface: bondctrlplane
