---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../catalog/advanced-cluster-management/operator/overlays/release-2.9
  - ../../catalog/advanced-cluster-management/instance/base
  - 01-hiveoverride.yaml
  - 01-provisioningoverride.yaml
  - 02-agentserviceconfig.yaml
  - 03-clusterimageset.yaml
  # Remove comment if you are using LSO.
  # This manifest sets default storageclass
  # - 01-storageclass.yaml
