---
apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "yukon"
  namespace: "yukon"
spec:
  additionalNTPSources:
    - "2600:52:7:38::12"
  baseDomain: "cars2.lab"
  clusterImageSetNameRef: "openshift-4.18.26"
  clusterName: "yukon"
  clusterNetwork:
    - cidr: "10.128.0.0/14"
      hostPrefix: 23 
    - cidr: "fd01::/48"
      hostPrefix: 64
  clusterType: HighlyAvailable
  cpuPartitioningMode: AllNodes
  extraLabels:
    ManagedCluster:
      siteName: "5g-core"
      logicalGroup: "active"
      common-418-disconnected: "false"
      common-418-resource-usage-test: ""
  holdInstallation: false
  installConfigOverrides: |
    {
      "capabilities": {
        "baselineCapabilitySet": "None",
        "additionalEnabledCapabilities": [
          "NodeTuning",
          "OperatorLifecycleManager",
          "Ingress"
        ]
      }
    }
  machineNetwork:
    - cidr: "192.168.38.0/26"  # based on CARS2 notes
    - cidr: "2600:52:7:238::0/64" # based on iDRAC
  networkType: "OVNKubernetes"
  pullSecretRef:
    name: "assisted-deployment-pull-secret"
  serviceNetwork:
    - cidr: "172.30.0.0/16"
    - cidr: "fd02::/112"
  sshPublicKey: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCdbJDYY43Zu0EKAGgrSKEobyXIxdhT0AeTT3yBoNY+YdYDScimJsQzK4hKNJIn1xC3klr0dSnsqeJru+SA4GMhbdcsmVyudhutCw75R/vFoRHOwaeVS2SMiBAtDbAYGQ3dh6LapkmXeLURcycNbebUV4HM9XsYqnuL8J2XyY4tRKgHrAd6OQw4jsXDOxwTRlHM822N/2kgv8iEwiXAJoUoymbr8mnfSxuuaH0oiKBwuaK1wuaDrlJyXkXNslPq89/1f8hJfjixY2dQdW7Xk5m3t5ptQxWENpw79OMRJ4cDW4G7LrtFONom5KQ+9TBZJIhNgJobkqI4qwinrWF8qMW5"
  templateRefs:
    - name: ai-cluster-templates-v1
      namespace: open-cluster-management
  nodes:
    - automatedCleaningMode: "disabled"
      bmcAddress: "idrac-virtualmedia://192.168.38.74/redfish/v1/Systems/System.Embedded.1"
      bmcCredentialsName:
        name: "yukon-cwl"
      bootMACAddress: ""
      bootMode: "UEFI"
      hostName: "yukon.cars2.lab"
      ignitionConfigOverride: "<STRING_REDACTED>"
      nodeNetwork:
        interfaces:
          - name: "eno12339"
            macAddress: "b4:96:91:c8:a2:7c"
          - name: "eno12409"
            macAddress: "b4:96:91:c8:a2:7d"
        config:
          interfaces:
            - name: eno12339
              type: ethernet
              state: up
              ipv4:
                address: 192.168.38.24
                enabled: true
                dhcp: false
              ipv6:
                address:
                  - ip: 2600:52:7:238::24
                    prefix-length: 64
                dhcp: false
                autoconf: false
                enabled: true
            - name: eno12409
              type: ethernet
              state: up
              ipv4:
                enabled: false
                dhcp: false
              ipv6:
                dhcp: false
                autoconf: false
                enabled: false
          dns-resolver:
            config:
              server:
                - 2600:52:7:59::11
          routes:
            config:
              - destination: '::/0'
                next-hop-address: '2600:52:7:59::1'
                next-hop-interface: ens2f0
      role: "master"
      rootDeviceHints:
        deviceName: ""
      templateRefs:
        - name: ai-node-templates-v1
          namespace: open-cluster-management
    - bmcAddress: "idrac-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/mno2-master1"
    bmcCredentialsName:
      name: "mno2-bmc-credentials"
    bootMACAddress: "AA:AA:AA:AA:03:02"
    bootMode: "UEFI"
    hostName: "mno2-master1.5g-deployment.lab"
    nodeLabels:
      5gran.lab/my-custom-label: ""
    nodeNetwork:
      config:
        interfaces:
        - ipv4:
            dhcp: false
            enabled: false
          ipv6:
            enabled: false
          name: "enp1s0"
          state: "up"
          type: "ethernet"
      interfaces:
      - macAddress: "AA:AA:AA:AA:03:02"
        name: "enp1s0"
    role: "master"
    rootDeviceHints:
      deviceName: "/dev/vda"
    templateRefs:
    - name: "ai-node-templates-v1"
      namespace: "open-cluster-management"
    - bmcAddress: "idrac-virtualmedia://192.168.125.1:9000/redfish/v1/Systems/local/mno2-master1"
    bmcCredentialsName:
      name: "mno2-bmc-credentials"
    bootMACAddress: "AA:AA:AA:AA:03:02"
    bootMode: "UEFI"
    hostName: "mno2-master1.5g-deployment.lab"
    nodeLabels:
      5gran.lab/my-custom-label: ""
    nodeNetwork:
      config:
        interfaces:
        - ipv4:
            dhcp: false
            enabled: false
          ipv6:
            enabled: false
          name: "enp1s0"
          state: "up"
          type: "ethernet"
      interfaces:
      - macAddress: "AA:AA:AA:AA:03:02"
        name: "enp1s0"
    role: "master"
    rootDeviceHints:
      deviceName: "/dev/vda"
    templateRefs:
    - name: "ai-node-templates-v1"
      namespace: "open-cluster-management"
    